== What is a CDB Conformant Data Store?

A CDB footnote:[Formerly known as Common Database the OGC Members determined that going forward that this standard shall be known as “CDB”.] conformant data store provides a representation of the whole earth optimized for very high speed access and visualization. The physical data store model divides the earth geographically into geodetic
tiles. Each tile is defined by a latitude/longitude boundary. Each tile contains one or more specific sets of features. The CDB model uses the WGS-84 coordinate reference system (CRS). Details of the model along with implementation requirements are provided in Volume 1: OGC CDB Core [16-113r3]. Any simulator client-devices access CDB geospatial content using a WGS-84 CRS based indexing and tiling scheme. The physical and logical tiling system specified in the CDB standard is similar to an equal area implementation of a Discrete Global Grid System (DGGS) footnote:[Please go to http://www.opengeospatial.org/projects/groups/dggsswg for information on an OGC candidate DGGS standard.]. However, the implementation predates the OGC DGGS standards work and as such does not implement all the OGC DGGS requirements.

A CDB data store contains the features and modeled representation of the synthetic environment. A CDB data store can contain:

* terrain altimetry,
* planimetry,
* raster imagery,
* attribution,
* 3D features with their modeled geometry,
* texture and attribution.

This standard also makes provision for the representation of moving models. An example of a moving model is a tank moving across the terrain as viewed by a helicopter pilot. The representation of moving models is comprehensive and goes well beyond other visualization standards because it makes provisions for the standardized naming conventions, material and feature attribution, radar/laser reflectivity, aircraft and airport lighting systems, armaments, special effects, collision points/volumes just to name a few. These provisions ensure interoperable simulation applications that are accessing a CDB structured data store.

The CDB standard governs all requirements of the CDB data store, as follows:

* Data content and representation of the synthetic environment;
* Structure and organization of the synthetic environment; and
* File format of the synthetic environment as stored on media.

The CDB standard describes a modeled environment representation for distributed simulation applications. The Section titled "<<UseOfCDBInApplicationsRequiringDynamicSyntheticEnvironments>>" discusses how a CDB-compliant simulator could be adapted to handle modifications of the synthetic environment in real-time.

Given that a CDB data store defines a structured storage structure for representation and attribution of terrain, geographic objects, moving objects and entities, it is possible to design a broad range of synthetic environment simulations that modify synthetic environments in real-time. Such simulations can modify the CDB data store and then notify other systems in a simulation federate footnote:[This usage of federate and federation comes from IEEE Std 1516 in the context of Federation Object Models (FOM) and Simulation Object Models (SOM). Common HLA terminology: Federate - an HLA compliant simulation entity. Federation - multiple simulation entities connected via the RTI using a common OMT.] that share a CDB data store about the changes. This provides a synthetic environment (SE) that is persistent and fully correlated across all simulation federates. For example, terrain “trafficability” could be handled by a new SE simulation that dynamically calculates soil moisture content as a function of localized rain precipitation and soil types/composition. A second simulation would then derive the resulting soil physics and determine vehicle wheel slippage across the varying terrain conditions.

The modification/notification approach is well-suited for a broad gamut of simulations. However, some simulations are very data intensive and require excessive broadcasting bandwidths to other federates. In such cases, these dynamic simulations would have to be replicated in the other client-devices of the federation. Good examples of this are visual system special effects (e.g., rotor downwash effect, missile plumes, muzzle flashes, cast landing lights). Typically such simulations are proprietary and intrinsic to the client-devices. Other examples of this include the varying effects of weather footnote:[Time-varying weather simulation effects could be simulated by a “weather server” simulation subsystem which in turn can rely on the terrain elevation and terrain material datasets to perform its simulation of weather in real-time.] (local winds, temperature, humidity, particulates, etc.) and oceans (currents, temperature, etc.).

For ease of editing and review, the standard has been separated into 15 document Volumes and a schema repository.

* Volume 0: OGC CDB Companion Primer for the CDB standard (Best Practice).
* Volume 1: OGC CDB Core Standard: Model and Physical Data Store Structure. The main body (core) of the CDB standard (Normative).
* Volume 2: OGC CDB Core Model and Physical Structure Annexes (Best Practice).
* Volume 3: OGC CDB Terms and Definitions (Normative).
* Volume 4: OGC CDB Rules for Encoding CDB Vector Data using Shapefiles (Best Practice).
* Volume 5: OGC CDB Radar Cross Section (RCS) Models (Best Practice).
* Volume 6: OGC CDB Rules for Encoding CDB Models using OpenFlight (Best Practice).
* Volume 7: OGC CDB Data Model Guidance (Best Practice).
* Volume 8: OGC CDB Spatial Reference System Guidance (Best Practice).
* Volume 9: OGC CDB Schema Package: http://schemas.opengis.net/cdb/ provides the normative schemas for key features types required in the synthetic modeling environment. Essentially, these schemas are designed to enable semantic interoperability within the simulation context (Normative).
* Volume 10: OGC CDB Implementation Guidance (Best Practice).
* Volume 11: OGC CDB Core Standard Conceptual Model (Normative).
* Volume 12: OGC CDB Navaids Attribution and Navaids Attribution Enumeration Values (Best Practice).
* Volume 13: OGC CDB Rules for Encoding CDB Vector Data using GeoPackage (Normative, Optional Extension).
* Volume 14: OGC CDB Guidance on Conversion of CDB Shapefiles into CDB GeoPackages (Best Practice).
* OGC CDB Optional Multi-Spectral Imagery Extension (Normative, Optional Extension).

=== Key and really important information - CDB dataset codes

The table below summarizes the CDB dataset codes along with their names
and their applicability to the community 3.0 specification and the OGC
standard, which is based on CDB version 3.2.

{set:cellbgcolor:white}
[cols=",,,",options="header",]
|====================================
2+|*Dataset*
2+|*Specification*
|*Name* |*Code* |*3.0* |*OGC*
|Elevation |001 |√ |√
|MinMaxElevation |002 |√ |√
|MaxCulture |003 |√ |√
|Imagery |004 |√ |√
|RMTexture |005 |√ |√
|RMDescriptor |006 |√ |√
|Reserved{set:cellbgcolor:red} |007 | |
|Reserved |008 | |
|Reserved |020 | |
|GSFeature{set:cellbgcolor:white}|100 |√ |√
|GTFeature |101 |√ |√
|GeoPolitical |102 |√ |√
|VectorMaterial |200 |√ |√
|RoadNetwork |201 |√ |√
|RailRoadNetwork |202 |√ |√
|PowerLineNetwork |203 |√ |√
|HydrographyNetwork |204 |√ |√
|GSModelGeometry |300 |√ |√
|GSModelTexture |301 |√ |√
|GSModelSignature |302 |√ |√
|GSModelDescriptor |303 |√ |√
|GSModelMaterial |304 | |√
|GSModelInteriorGeometry |305 | |√
|GSModelInteriorTexture |306 | |√
|GSModelInteriorDescriptor |307 | |√
|GSModelInteriorMaterial |308 | |√
|GSModelCMT |309 | |√
|T2DModelGeometry |310 | |√
|GSModelInteriorCMT |311 | |√
|T2DModelCMT |312 | |√
|T3DModelGeometry |320 | |√
|T3DModelTexture |321 | |√
|T3DModelMaterial |322 | |√
|T3DModelInteriorGeometry |323 | |√
|T3DModelInteriorTexture |324 | |√
|T3DModelInteriorMaterial |325 | |√
|NavData |400 |√ |√
|Navigation |401 |√ |√
.2+|GTModelGeometry |500 |√ |√
|510 | |√
.2+|GTModelTexture |501 |√ |{set:cellbgcolor:grey}
|{set:cellbgcolor:white}511 | |√
.2+|GTModelSignature |502 |√ |{set:cellbgcolor:grey}
|{set:cellbgcolor:white}512 | |√
|GTModelDescriptor |503 |√ |√
|GTModelMaterial |504 | |√
|GTModelCMT |505 | |√
|GTModelInteriorGeometry |506 | |√
|GTModelInteriorTexture |507 | |√
|GTModelInteriorDescriptor |508 | |√
|GTModelInteriorMaterial |509 | |√
|GTModelInteriorCMT |513 | |√
|MModelGeometry |600 |√ |√
|MModelTexture |601 |√ |√
.2+|MModelSignature |602 |√ |{set:cellbgcolor:grey}
|{set:cellbgcolor:white}606 | |√
|MModelDescriptor |603 |√ |√
|MModelMaterial |604 | |√
|MModelCMT |605 | |√
|Metadata |700 | |√
|ClientSpecific |701 | |√
|Reserved for CDB Extensions {set:cellbgcolor:red}|9xx | |
|====================================


[cols=",",options="",]
|============================
|{set:cellbgcolor:white} |Dataset Code is not used
| |
|√ |Dataset Code is in use
| |
|{set:cellbgcolor:grey}|Dataset Code is deprecated
| {set:cellbgcolor!}|
|{set:cellbgcolor:red} |Dataset Code is reserved
|============================

{set:cellbgcolor!}
